version: '3'
services: 
  web:
    build:
      context: . # Where files and folder come from
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes: 
      - /app/node_modules # Do not sycn volumes
      - .:/app # Sync app folder
  tests:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes: 
      - /app/node_modules # Do not sycn volumes
      - .:/app # Sync app folder
    command: ["yarn", "test"]
